### PR TITLE
adding schema for obligation

### PR DESCRIPTION
**Pull request by njkmr0027**

### CODE REVIEW

**Review by vksiva — APPROVED** [review]
Changes look good.

**Comment by RoAnnC1** [comment]
@njkmr0027 You'll need to sign the CLA before this pull request can be merged. Also, please do not add extra spacing in tables, widths are auto set by the CSS and this just makes them difficult to review.

**Comment by njkmr0027** [comment]
Hi RoAnnC1 ,

I have signed the CLA as shown:
image


but still getting below error:
image

**Review by vksiva — APPROVED** [review]
Looks good.

**Review by RoAnnC1 — APPROVED** [review]
:shipit:

**Pull request merged**
