### PR TITLE
FINS-10923: Update v4.financial-integration.markdown

### PR DESCRIPTION
**Pull request by SleepyS3a**
Updated ignore doc status description

### CODE REVIEW

**Comment by RoAnnC1** [comment]
@SleepyS3a The email you used to create the commit  is not associated with your GitHub account. Make sure to add (and verify) your email to your GitHub account.
Afterwards you can trigger a recheck via https://cla-assistant.io/check/SAP-docs/preview.developer.concur.com?pullRequest=1053

**Comment by SleepyS3a** [comment]
Hello @RoAnnC1 I have added my SAP email to my git account, but the link to retrigger the check does not work.  What should I do?

**Comment by RoAnnC1** [comment]
@SleepyS3a Not sure why the retrigger didn't work, but it shows you've signed the CLA and all automated checks have passed.

**Review by RoAnnC1 — APPROVED** [review]
:shipit:

**Pull request merged**
