### PR TITLE
ATTEND-1013 An attendee's type ID cannot be updated

### PR DESCRIPTION
**Pull request by victoriousxd**
Update v3.attendees.markdown

### CODE REVIEW

**Review by RoAnnC1 — DISMISSED** [review]
:shipit:

**Comment by victoriousxd** [comment]
peer reviewed by @chandra-nadukula @rogerdsap

**Review by chandra-nadukula — APPROVED** [review]

**Comment by victoriousxd** [comment]
Hi @RoAnnC1, sorry for the back and forth on this
this has been peer reviewed and is ready to be merged.

**Review by RoAnnC1 — APPROVED** [review]
:shipit:

**Pull request merged**
