### PR TITLE
Added new ESS certificate

### PR DESCRIPTION
**Pull request by usandre**

### CODE REVIEW

**Review by RoAnnC1 — CHANGES_REQUESTED** [review]
Some typos in Line 62, please change to the below. 
We strongly recommend you use the certificate Common Name as the authentication mechanism. If you rely on the certificate Serial Number or the certificate itself, please be aware that at the beginning of each year the certificate will be re-issued and you have to update your authentication mechanisms.

**Comment by usandre** [comment]
@RoAnnC1 thank you. updated!

**Review by RoAnnC1 — COMMENTED** [review]
@usandre You need to sign the CLA before I can merge this.

**Review by RoAnnC1 — APPROVED** [review]
:shipit:

**Pull request merged**
