### PR TITLE
add POST endpoint

### PR DESCRIPTION
**Pull request by wade-richards**

### CODE REVIEW

**Review by RoAnnC1 — APPROVED** [review]
:shipit:

**Comment by RoAnnC1** [comment]
@wade-richards I'll merge this for you once it's no longer in Draft. If you're still working on it, no problem.

**Comment by wade-richards** [comment]
> @wade-richards I'll merge this for you once it's no longer in Draft. If you're still working on it, no problem.

The change to the API itself hasn't released yet, so I assume we want to keep the documentation change back until the API has changed.  It'll probably be blocked until January, since I'm about to start my winter vacation, and I don't think it's good to commit changes hours before a 3 week vacation.

**Comment by wade-richards** [comment]
The change is merged into the code, and should go live the next release of Concur Travel and Expense.  The docs can be updated now.

**Pull request merged**
