### PR TITLE
AIS-9091 Improve Partner Documentation for FIP

### PR DESCRIPTION
**Pull request by denitsastoy**
Describe the change:
Updated the documentation. Added more clarity around the API and events purpose. Added diagrams to show the process flow with events.

What are the acceptance criteria for this change:
Better documentation for the Developer portal

How was this tested, and what to look for when testing: N/A

### CODE REVIEW

**Comment by denitsastoy** [comment]
hi @jonikamelcher my IDE is changing the table markup. I still see all tables as tables in the Rich Diff and in Macdown
image

**Comment by jonikamelcher** [comment]
Hi @denitsastoy. Correct. They still display through GitHub, however it makes it extremely difficult for the writers to edit and review the material and our website isn't always as forgiving when it publishes. It also highlights a lot of changes that are not actually changes. Do you have a way to remove this? We can navigate  around it this time if we have to, but if it can't be remedied we ask you add your changes manually.

**Comment by denitsastoy** [comment]
@jonikamelcher ok I see. Let me see if I can revert just these changes.

**Comment by denitsastoy** [comment]
@jonikamelcher removed the table changes that were just formatting

**Comment by jonikamelcher** [comment]
@denitsastoy You are an absolute hero. Thank you so much. We greatly appreciate it.

**Pull request merged**
