### PR TITLE
Cash Advance v4.1 markdown file

### PR DESCRIPTION
**Pull request by YakuChen**

### CODE REVIEW

**Comment by YakuChen** [comment]
Cash Advance 4.1 (remove extra 'value' field in GET, change 'amount' field in POST to string)

**Comment by jonikamelcher** [comment]
Hi @YakuChen. Are you able to provide an updated Swagger file as well? Thank you.

**Comment by YakuChen** [comment]
Hi @jonikamelcher , I've recorded the swagger link in API launch checklist
https://wiki.concur.com/confluence/display/GPTE/Cash+Advance%3A+v4.1+Launch+Checklist

**Comment by jonikamelcher** [comment]
Hi @YakuChen. Please add the file to the repository under the api-explorer section.

**Review by RoAnnC1 — APPROVED** [review]
:shipit:

**Pull request merged**
