### PR TITLE
ATTEND-1075 - Attendee API scopes documentation

### PR DESCRIPTION
**Pull request by chandra-nadukula**
#### ATTEND-1075
- Add documentation for the new scopes necessary for V4 Attendee API's.
- Update existing `ATTEND` scope documentation.

### CODE REVIEW

**Review by victoriousxd — APPROVED** [review]

**Review by RoAnnC1 — APPROVED** [review]
:shipit:

**Comment by chandra-nadukula** [comment]
@RoAnnC1 I don't my changes in developer.concur.com, anything we are missing after the merge in terms of process?

**Comment by RoAnnC1** [comment]
I am not sure why it's not showing up. We had a bunch of issues with the build process last week. I'll take a look and update as needed.

**Comment by chandra-nadukula** [comment]
Thanks RoAnn!

**Pull request merged**
